// <auto-generated />
using System;
using DietiEstate.Shared.Models.UserModels;
using DietiEstate.WebApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DietiEstate.WebApi.Migrations
{
    [DbContext(typeof(DietiEstateDbContext))]
    partial class DietiEstateDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "user_role", new[] { "admin", "agent", "client", "super_admin" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DietiEstate.Shared.Models.ListingModels.Listing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("AgentUserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Available")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<decimal>("Dimensions")
                        .HasColumnType("numeric");

                    b.Property<bool>("Elevator")
                        .HasColumnType("boolean");

                    b.Property<string>("EnergyClass")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("FeaturedImage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Floor")
                        .HasColumnType("integer");

                    b.Property<float>("Latitude")
                        .HasColumnType("real");

                    b.Property<float>("Longitude")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("OwnerEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("Rooms")
                        .HasColumnType("integer");

                    b.Property<Guid>("TypeId")
                        .HasColumnType("uuid");

                    b.Property<int>("Views")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AgentUserId");

                    b.HasIndex("TypeId");

                    b.ToTable("Listing", (string)null);
                });

            modelBuilder.Entity("DietiEstate.Shared.Models.ListingModels.PropertyType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("PropertyType", (string)null);
                });

            modelBuilder.Entity("DietiEstate.Shared.Models.ListingModels.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Service", (string)null);
                });

            modelBuilder.Entity("DietiEstate.Shared.Models.ListingModels.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Tag", (string)null);
                });

            modelBuilder.Entity("DietiEstate.Shared.Models.Shared.Image", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Url")
                        .IsUnique();

                    b.ToTable("Image", (string)null);
                });

            modelBuilder.Entity("DietiEstate.Shared.Models.UserModels.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<UserRole>("Role")
                        .HasColumnType("user_role");

                    b.HasKey("Id");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("ListingImage", b =>
                {
                    b.Property<Guid>("ListingImagesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ListingsId")
                        .HasColumnType("uuid");

                    b.HasKey("ListingImagesId", "ListingsId");

                    b.HasIndex("ListingsId");

                    b.ToTable("ListingImage", (string)null);
                });

            modelBuilder.Entity("ListingService", b =>
                {
                    b.Property<Guid>("ListingServicesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ListingsId")
                        .HasColumnType("uuid");

                    b.HasKey("ListingServicesId", "ListingsId");

                    b.HasIndex("ListingsId");

                    b.ToTable("ListingService", (string)null);
                });

            modelBuilder.Entity("ListingTag", b =>
                {
                    b.Property<Guid>("ListingTagsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ListingsId")
                        .HasColumnType("uuid");

                    b.HasKey("ListingTagsId", "ListingsId");

                    b.HasIndex("ListingsId");

                    b.ToTable("ListingTag", (string)null);
                });

            modelBuilder.Entity("DietiEstate.Shared.Models.ListingModels.Listing", b =>
                {
                    b.HasOne("DietiEstate.Shared.Models.UserModels.User", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DietiEstate.Shared.Models.ListingModels.PropertyType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("ListingImage", b =>
                {
                    b.HasOne("DietiEstate.Shared.Models.Shared.Image", null)
                        .WithMany()
                        .HasForeignKey("ListingImagesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DietiEstate.Shared.Models.ListingModels.Listing", null)
                        .WithMany()
                        .HasForeignKey("ListingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ListingService", b =>
                {
                    b.HasOne("DietiEstate.Shared.Models.ListingModels.Service", null)
                        .WithMany()
                        .HasForeignKey("ListingServicesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DietiEstate.Shared.Models.ListingModels.Listing", null)
                        .WithMany()
                        .HasForeignKey("ListingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ListingTag", b =>
                {
                    b.HasOne("DietiEstate.Shared.Models.ListingModels.Tag", null)
                        .WithMany()
                        .HasForeignKey("ListingTagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DietiEstate.Shared.Models.ListingModels.Listing", null)
                        .WithMany()
                        .HasForeignKey("ListingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
